
spring:
  redis:
    host: 175.27.243.243
    port: 6379
    password: 213879
    timeout: 1800000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 100000ms